version: "3.9"
networks:
  jedi:

services:
  app:
    container_name: padawan-61254-app
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile

  db:
    container_name: s21621611
    image: postgres:latest

    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: padawan
      POSTGRES_PASSWORD: R2D2c3p0
      POSTGRES_DB: tasks