version: "3"
networks:
  jedi:

services:
  db:
    container_name: 21621611
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tasks